create or replace PROCEDURE BL_FCC_GET_ALL_CLIENTS 
(
  in_CUSTOMER_NANE       IN varchar2 DEFAULT NULL
 ,OUT_RESULTADO OUT SYS_REFCURSOR
)
AS

BEGIN
--AH - 20180704- Modificaciones para incluir datos de fecha kyc, aml rating y tipo de clientes.
-- Query final a usar en el SP
-- AH - 20210305 - Usado tambien en el WS de IntegracionITIS
-- AH - 20230702 - Usado también en Generales\HTML\BusquedaCliente\ClientesBladex\ 
--  No cambiar el orden de las columnas 
-- AH 20221216 - Agregando CUST_CAN_BE_USE_NY_AGENCY
open out_resultado for 
SELECT CUST.CUSTOMER_NO -- 0
      , CUST.CUSTOMER_NAME1
      , CUST.FULL_NAME
      , UDF.FIELD_VAL_17 EXP_DATE
      ,(SELECT AUX1.CUSTOMER_NAME1 FROM STTM_CUSTOMER@LINK_BPMBLFCC AUX1 WHERE AUX1.CUSTOMER_NO =  UDF.FIELD_VAL_31  ) CLIENT_PRAL
      ,UDF.FIELD_VAL_31 CLIENT_PRAL_CODE       --5 
      ,CUST.CUSTOMER_TYPE
      ,CUST.RECORD_STAT
      ,CUST.AUTH_STAT
      ,UDF.FIELD_VAL_20 AML_RATING
      ,UDF.FIELD_VAL_39 LAST_KYC_DATE -- 10
      ,UDF.FIELD_VAL_42 TIPO_CLIENTE
      
      --El proceso de loans processing espera este formato 'YYYY-MM-DD' en este campo "FECHA_RENOVACION" 2018.10.31 Ticket: 13224 bmg
     --,to_char(ADD_MONTHS(TO_DATE(UDF.FIELD_VAL_39, 'YYYY-MM-DD')+1, (RAM.TIEMPO_RENOVACION*12)), 'YYYY-MM-DD') FECHA_RENOVACION   -- 12
     --,ADD_MONTHS(TO_DATE(UDF.FIELD_VAL_39, 'YYYY-MM-DD'), (RAM.TIEMPO_RENOVACION*12))- trunc(sysdate) DIAS_EXPIRADO 
     --2018.10.31 Ticket: 13224 bmg formato para mostrar en los formulario 'DD-MON-YYYY'
     --,to_char(ADD_MONTHS(TO_DATE(UDF.FIELD_VAL_39, 'YYYY-MM-DD')+1, (RAM.TIEMPO_RENOVACION*12)), 'DD-MON-YYYY') FECHA_RENOV_FORMATEADA  
     
     --HLEE 04-09-2023: Ticket 38930
     ,TO_CHAR(FN_KCC_CALCULA_FVENCIMIENTO(UDF.FIELD_VAL_61,TO_CHAR(TO_DATE(UDF.FIELD_VAL_39, 'YYYY-MM-DD'), 'DD/MM/YYYY'),UDF.FIELD_VAL_20), 'YYYY-MM-DD') FECHA_RENOVACION
     ,FN_KCC_CALCULA_FVENCIMIENTO(UDF.FIELD_VAL_61,TO_CHAR(TO_DATE(UDF.FIELD_VAL_39, 'YYYY-MM-DD'), 'DD/MM/YYYY'),UDF.FIELD_VAL_20) - TRUNC(SYSDATE) DIAS_EXPIRADO
     ,TO_CHAR(FN_KCC_CALCULA_FVENCIMIENTO(UDF.FIELD_VAL_61,TO_CHAR(TO_DATE(UDF.FIELD_VAL_39, 'YYYY-MM-DD'), 'DD/MM/YYYY'),UDF.FIELD_VAL_20), 'DD-MON-YYYY') FECHA_RENOV_FORMATEADA
     
     ,UDF.field_val_43 as MONITOREO_TRANSAC --15
     --2020.04.27 bmg -- formularios electronicos
     ,(SELECT COMP_MIS_1  FROM   MITM_CUSTOMER_DEFAULT@LINK_BPMBLFCC WHERE CUSTOMER = CUST.CUSTOMER_NO) ACCOUNT_OFFICER
     ,CUST.CUSTOMER_CATEGORY
     --fin 2020.04.27
      ,UDF.FIELD_VAL_32 CUST_CAN_BE_USE_NY_AGENCY -- AH 20221216 - - Jorge Navarrete documentará este SP
      ,TIPO_CLT.LOV_DESC TIPO_CLIENTE_DESC --19
FROM STTM_CUSTOMER@LINK_BPMBLFCC CUST
LEFT JOIN CSTMS_FUNCTION_USERDEF_FIELDS@LINK_BPMBLFCC UDF ON 
            (UDF.FUNCTION_ID = 'STDCIF' AND UDF.REC_KEY = CUST.CUSTOMER_NO || '~')    
LEFT JOIN WF_LMC_RENOVACION_X_AML_RATING RAM ON UDF.FIELD_VAL_20 = RAM.RATING              
LEFT JOIN UDTM_LOV@LINK_BPMBLFCC TIPO_CLT ON   UDF.FIELD_VAL_42 = TIPO_CLT.LOV AND TIPO_CLT.FIELD_NAME = 'TIPO DE CLIENTE'
WHERE
 ( UPPER(CUST.CUSTOMER_NAME1) LIKE '%' || UPPER(in_CUSTOMER_NANE) || '%'
OR
  UPPER(CUST.FULL_NAME) LIKE '%' || UPPER(in_CUSTOMER_NANE) || '%' 
OR
  UPPER(CUST.CUSTOMER_NO) LIKE '%' || UPPER(in_CUSTOMER_NANE) || '%'  
  )

--CUST.CUSTOMER_TYPE = IN_CUSTOMER_TYPE AND 
--ROWNUM <= 1000
order by CUST.CUSTOMER_NO
;


END BL_FCC_GET_ALL_CLIENTS;