create or replace PROCEDURE "BL_KCC_CUSTOMER_BUSCA_RECIENTE" 
(  in_CUSTOMER_NO IN number DEFAULT NULL
  ,in_ID_SOLICITUD IN VARCHAR2 DEFAULT NULL
  ,in_CUSTOMER_NO_FCC IN VARCHAR2 DEFAULT NULL
  ,out_resultado OUT SYS_REFCURSOR
) AS
--Renova
--Aserrano: Se cambia el nombre del UDF colocandole guion bajo
V_CUSTOMER_NUMBER_MAIN INTEGER;
V_OLD_ID_CUSTOMER NUMBER;
V_ID_SOLICITUD VARCHAR(20);
V_OUT_RESULTADO SYS_REFCURSOR;

/************
  APitty
  Es una copia de BL_KCC_CUSTOMER_BUSCA_LOCAL y se creo para buscar un cliente
  especifico por numero de cliente en FCC sin afectar lo de produccion.
*************/

BEGIN
  BEGIN
    SELECT CUSTOMER_NO INTO V_CUSTOMER_NUMBER_MAIN 
    FROM WF_KCC_CUSTOMER_INFO 
    WHERE ID_SOLICITUD = in_ID_SOLICITUD
          AND MAIN_CUSTOMER = 1;
    
    EXCEPTION WHEN NO_DATA_FOUND THEN 
    V_CUSTOMER_NUMBER_MAIN := 0;
    
    BL_KCC_BUSCA_MAX_SOLICITUD(
                      IN_CUSTOMER_NO_FCC => IN_CUSTOMER_NO_FCC,
                      OUT_ID_SOLICITUD => V_ID_SOLICITUD,
                      OUT_ID_CUSTOMER => V_OLD_ID_CUSTOMER,
                      OUT_RESULTADO => V_OUT_RESULTADO
                      );
  END;
       
  OPEN out_resultado FOR
    SELECT ID_SOLICITUD,
           CUST.CUSTOMER_NO,                    	   	CUST.SHAREHOLDER, 	              NVL(CUST.CUSTOMER_TYPE, KCT.CUSTOMER_ID) CUSTOMER_TYPE,
           CUST.CUSTOMER_NAME1,                 			CUST.FULLNAME,               
           CUST.TAXIDNUMBER,                   				CUST.DV,                          CUST.CUSTOMER_CATEGORY,          
           CUST.RELATIONTYPE,                   			CUST.INDUSTRY,                    CUST.NAMEOFECONOMICGROUP,    
           CUST.LEGALREPRESENTATIVE,           				CUST.NAMEEXTERNALAUDITORS,        CUST.NAMEINTERNATIONALRISK,
           CUST.POSTALALINE1,                   			CUST.POSTALALINE2,                CUST.POSTALALINE3,
           CUST.POSTALACITY,                    			CUST.PHYSICALALINE1,              CUST.PHYSICALALINE2,
           CUST.PHYSICALALINE3,                 			CUST.TELEPHONENUMBER,             CUST.TELEPHONENUMBER2,
           CUST.FAXNUMBER,                      			CUST.WEBSITE,                     CUST.DEFAULT_MEDIA,
           CUST.INCORP_COUNTRYID,               			TO_CHAR(CUST.INCORP_DATE, 'dd/MON/yyyy') INCORP_DATE,                 
           CUST.RESIDENCECOUNTRY,
           FN_BUSCA_COUNTRY_DESCR(cUST.RESIDENCECOUNTRY) RESCTRY_DESC,
           CUST.NATIONALITYID,                  		 	FN_BUSCA_COUNTRY_DESCR(CUST.NATIONALITYID) NATIONALITYIDDESCR,
           CUST.RESIDENCELOCATIONID, 		 			  	    FN_BUSCA_RES_LOCATION(cUST.RESIDENCELOCATIONID) RESLOC_DESC,   
           CUST.LANGUAGEID,									          (SELECT LANG_NAME FROM SMTB_LANGUAGE@LINK_BPMBLFCC WHERE  LANG_CODE=  CUST.LANGUAGEID)LANGUAGEID_DESC,
           CUST.BANKTYPE,                       		  CUST.TYPEOFLICENCE,   			      CUST.SWIFT_CODE,						
           CUST.ABACODEVALUE,                   		  CUST.COMPLIANCEOFFICER,           CUST.ADDRESSPROCESSAGENTINUSA,		
           trim(CUST.NETWORTH)NETWORTH,               CUST.EXPOSURE_COUNTRYID, 		      FN_BUSCA_COUNTRY_DESCR(EXPOSURE_COUNTRYID) EXPCTRY_DESC, 
           TO_CHAR(CUST.INCEPTION_DATE, 'dd/MON/yyyy') INCEPTION_DATE,								        
           CUST.PRODUCT_SERVICE_OFFERED,        		  CUST.RELATEDCOMPANIES,            
           CUST.EMAIL,										            CUST.NAME_ADDRESS_LEGAL_ADVISOR,     		  CUST.REFERENCE_BANKING_COMMERCIAL REFERENCE_BANKING_COMME,
           CUST.NAME_OF_STOCK,                  			CUST.COUNTRIES_WHERE_OFFERS,     			    CUST.REGULATORY_AUTHORITY,
           CUST.RELATEDACCOUNT,								        FN_BUSCA_COUNTRY_DESCR(CUST.INCORP_COUNTRYID) INCORP_CNTRY_DESC,		 
           CUST.MAIN_CUSTOMER, 								        IND.CODE_DESC INDUSTRY_DESC, -- Industry Description
           CUST.TELEPHONENUMBER || '|' || CUST.TELEPHONENUMBER2 || '|' || CUST.FAXNUMBER || '|' || CUST.WEBSITE || '|' || CUST.EMAIL TELFAXWEBEMAIL,
           RTRIM(CUST.POSTALALINE1   || ' ' ||  CUST.POSTALALINE2   || ' ' || CUST.POSTALALINE3   || ' ' || CUST.POSTALACITY  || ' | ' || 
           CUST.PHYSICALALINE1  || ' ' || CUST.PHYSICALALINE2  || ' ' ||  CUST.PHYSICALALINE3) ADDRESS,
            CASE WHEN CUST.CHK_SAMESHOLDERS_MAINCUST = '1' THEN FN_KCC_BUSCA_MANAG_DIRECTORS(1,V_CUSTOMER_NUMBER_MAIN, in_ID_SOLICITUD)
           ELSE FN_KCC_BUSCA_MANAG_DIRECTORS(1,CUST.CUSTOMER_NO, in_ID_SOLICITUD) END BOARDOFDIRECTORS,
            CASE WHEN CUST.CHK_SAMESHOLDERS_MAINCUST = '1' THEN FN_KCC_BUSCA_MANAG_DIRECTORS(2,V_CUSTOMER_NUMBER_MAIN, in_ID_SOLICITUD)
           ELSE FN_KCC_BUSCA_MANAG_DIRECTORS(2,CUST.CUSTOMER_NO, in_ID_SOLICITUD) END TOPMANAGEMENT,
           CUST.CUSTOMER_NO_FCC,				                  CUST.SHORT_NAME,					CUST.LIAB_ID,				  
           CUST.GROUP_CODE,						                    CUST.ID_SOLICITUD_LM,     CUST.ACCOUNT_OFFICERID
           ,CUST.ADDRESSPROCESSAGENTINUSA USA_PROCESS_AGENT
             ,NVL(CT.CUSTOMER_DESCRIPTION,                KCT.CUSTOMER_DESCRIPTION) CUSTOMER_TYPE_DESC,         CUST.ID_EXISTE_FCC
           ,UDFD.lov_desc BankType_DESC,                  CUST.LOCATIONID,                       CUST.AML_RATINGID
           ,DEM.description DEFAULT_MEDIA_DESC,           CUST.NY_AGENCY,                        CUST.SBP_CATEGORYID
           ,UDFD2.lov_desc RELATIONTYPE_DESC,             CUST.CUSTOMER_CLASSIFICATION_PEP,      CUST.DESCRIPCION_PEP
           ,CCAT.CUST_CAT_DESC CUSTOMER_CATEGORY_DESC,    CUST.INCORPORATION_PURPOSE,            ACCOFFI.CODE_DESC OFFICER_DESCRIPTION
           ,CUST.SUB_ECOGR_CD,                            LOC.CODE_DESC LOCATION_DESCRIPTION,    AML.LOV_DESC AML_DESCRIPTION
           ,CUST.ECONOMICGROUPRUC,                        SBP.CATEGORY_DESCRIPCION SBP_CATEGORY_DESCRIPTION,         CUST.LEGALREPRESENTATIVE_INFO
           ,CUST.LAST_CHANGE_DATE,                        CUST.DIGNATARIES,                       CUST.POWER_DEES
           ,CUST.CHK_CREATE_FCC,                          CUST.AUTHORIZED_SIGNATURES,             CUST.RELATION_CORRESPONSAL
           ,CUST.CHK_SAMESHOLDERS_MAINCUST   
           ,CASE WHEN CUST.CHK_SAMESHOLDERS_MAINCUST = '1' THEN FN_KCC_BUSCA_SHAREHOLDERS(V_CUSTOMER_NUMBER_MAIN, in_ID_SOLICITUD,2)
           ELSE FN_KCC_BUSCA_SHAREHOLDERS(in_CUSTOMER_NO, in_ID_SOLICITUD,2) END SHAREHOLDERS
           ,CUST.GROUP_EXPIRATION_MONTH -- HLEE - 30-08-2023 Ticket 38930
    FROM WF_KCC_CUSTOMER_INFO CUST 
      --LEFT OUTER JOIN DIM_CUSTOMER@LINK_BPMBLFCC DIMC                 ON  CUST.CUSTOMER_NO_FCC  = DIMC.V_CUSTOMER_CODE
      LEFT OUTER JOIN GLTM_MIS_CODE@LINK_BPMBLFCC IND                 ON CUST.INDUSTRY = IND.MIS_CODE
      LEFT OUTER JOIN WF_KCC_CUSTOMER_TYPE CT                         ON CUST.CUSTOMER_TYPE = CT.CUSTOMER_ID    
      LEFT OUTER JOIN cstm_function_userdef_fields@LINK_BPMBLFCC UDF ON CUST.CUSTOMER_NO||'~' = UDF.REC_KEY
      LEFT OUTER JOIN udtm_lov@link_bpmblfcc UDFD                     ON UDF.FIELD_VAL_7 = UDFD.LOV AND  UDFD.field_name = 'BANK_TYPE'
      LEFT OUTER JOIN WF_KCC_DFLT_MEDIA DEM                           ON CUST.DEFAULT_MEDIA = DEM.MEDIA
      LEFT OUTER JOIN udtm_lov@link_bpmblfcc UDFD2                    ON CUST.RELATIONTYPE = UDFD2.LOV AND UDFD2.field_name = 'RELATION_TYPE'
      LEFT OUTER JOIN STTM_CUSTOMER_CAT@link_bpmblfcc CCAT            ON CUST.CUSTOMER_CATEGORY = CCAT.CUST_CAT AND CCAT.record_stat = 'O' AND CCAT.auth_stat = 'A'
      LEFT OUTER JOIN WF_LMT_CUSTOMER_TYPE CLT                        ON TRIM(CLT.CO_CUSTOMER_TYPE) = TRIM(CUST.LMT_CUSTOMER_TYPE)
      LEFT OUTER JOIN WF_KCC_CUSTOMER_TYPE KCT                        ON KCT.CUSTOMER_ID = CLT.CO_CUSTOMER_TYPE_KCC
      LEFT OUTER JOIN GLTM_MIS_CODE@LINK_BPMBLFCC ACCOFFI             ON ACCOFFI.MIS_CODE = CUST.ACCOUNT_OFFICERID
      LEFT OUTER JOIN GLTM_MIS_CODE@LINK_BPMBLFCC LOC                 ON LOC.MIS_CODE = CUST.LOCATIONID
      LEFT OUTER JOIN udtm_lov@link_bpmblfcc AML                      ON AML.LOV = CUST.AML_RATINGID AND AML.FIELD_NAME = 'AML_RISK_RATING'
      LEFT OUTER JOIN WF_KCC_SBP_CATEGORY SBP                         ON SBP.CATEGORYID = CUST.SBP_CATEGORYID
    WHERE
      ID_SOLICITUD = NVL(V_ID_SOLICITUD, ID_SOLICITUD) AND 
      CUST.LMT_CUSTOMER_TYPE <> 'G' AND
      CUST.CUSTOMER_NO = V_OLD_ID_CUSTOMER AND
      (CUSTOMER_NO_FCC = nvl(in_CUSTOMER_NO_FCC, CUSTOMER_NO_FCC) OR NVL(CUSTOMER_NO_FCC, 'XXXXXXXXX')= NVL(IN_CUSTOMER_NO_FCC, 'XXXXXXXXX'))
       ORDER BY CUST.MAIN_CUSTOMER DESC;
  
END BL_KCC_CUSTOMER_BUSCA_RECIENTE;